#!/bin/bash
go clean -r -x -cache -testcache -modcache
if [[ ! -e go.mod ]] ;
then
   go mod init
   go get ./...
fi

go mod download
go mod vendor

go get -u ./... && go mod download && go mod vendor
