name: "\U0001F41E Bug report"
description: Report an issue with golib
labels: ['triage: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce the bug/issue
      description: Give us a simple code example allowing to reproduce the bug/issue
      placeholder: Reproduce
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: 'Please include logs  if any'
      render: shell

