/*
 * MIT License
 *
 * Copyright (c) 2024 Nicolas JUHEL
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

package pidcontroller

import "context"

// PID defines the interface for a Proportional-Integral-Derivative controller.
// It provides methods to generate a sequence of values transitioning from a start point
// to a target point, controlled by the PID algorithm.
type PID interface {
	// RangeCtx generates a slice of float64 values representing the progression from a minimum value
	// to a maximum value, utilizing the PID controller to determine the step size at each iteration.
	//
	// The provided context.Context allows for cancellation or timeout of the operation.
	// If the context is cancelled before the target is reached, the function returns the values
	// generated up to that point, appending the target value as the final element to ensure closure.
	//
	// Parameters:
	//   - ctx: The context to manage the lifecycle of the operation (e.g., timeout, cancellation).
	//   - min: The starting value (Process Variable initial state).
	//   - max: The target value (SetPoint).
	//
	// Returns:
	//   A slice of float64 containing the sequence of values generated by the PID controller.
	RangeCtx(ctx context.Context, min, max float64) []float64

	// Range acts as a wrapper around RangeCtx with a default timeout.
	// It generates a sequence of values from min to max.
	//
	// This method enforces a default timeout (e.g., 5 seconds) to prevent infinite loops
	// in case the PID controller fails to converge or the target is unreachable.
	//
	// Parameters:
	//   - min: The starting value.
	//   - max: The target value.
	//
	// Returns:
	//   A slice of float64 containing the sequence of values.
	Range(min, max float64) []float64
}

// New creates and initializes a new PID controller instance.
//
// The PID controller is initialized with the specified coefficients for the Proportional,
// Integral, and Derivative terms. These coefficients dictate the behavior of the controller:
//   - rateProportional (Kp): Reacts to the current error.
//   - rateIntegral (Ki): Reacts to the accumulation of past errors.
//   - rateDerivative (Kd): Reacts to the rate of change of the error.
//
// Parameters:
//   - rateProportional: The proportional gain coefficient.
//   - rateIntegral: The integral gain coefficient.
//   - rateDerivative: The derivative gain coefficient.
//
// Returns:
//
//	A new instance of the PID interface.
func New(rateProportional, rateIntegral, rateDerivative float64) PID {
	return &pid{
		kp: rateProportional,
		ki: rateIntegral,
		kd: rateDerivative,
	}
}
