/*
 * MIT License
 *
 * Copyright (c) 2020 Nicolas JUHEL
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *
 */

package pool

import (
	"sync"
	"sync/atomic"
)

// Pool defines a thread-safe repository for accumulating multiple errors.
//
// This interface is particularly useful in concurrent environments (like worker pools
// or parallel map-reduce operations) where multiple goroutines might encounter
// errors simultaneously. It provides a synchronized way to collect these errors
// without external mutex management.
//
// The Pool maintains:
//   - A sequence counter for automatic indexing (starts at 1).
//   - A high-water mark (MaxId) tracking the highest used index.
//   - A thread-safe storage map.
type Pool interface {
	// Add appends one or more errors to the collection.
	//
	// Each non-nil error is assigned a unique, sequential index generated by
	// an internal atomic counter. This is the preferred method for simple
	// error collection.
	//
	// Parameters:
	//   - e: A variadic list of errors to add. Nil errors are silently ignored.
	Add(e ...error)

	// Get retrieves a specific error from the pool by its index.
	//
	// Parameters:
	//   - i: The index of the error to retrieve.
	//
	// Returns:
	//   - The error if found at the given index, or nil if no error exists at that index
	//     or if the index is 0.
	Get(i uint64) error

	// Set explicitly places an error at the specified index.
	//
	// This method allows for manual indexing, which is useful when errors correspond
	// to specific IDs or positions in an input dataset. If an error already exists
	// at this index, it will be overwritten. This operation updates the internal
	// high-water mark (MaxId) but does not affect the sequence counter used by Add().
	//
	// Parameters:
	//   - i: The manual index to use.
	//   - e: The error to store. Nil errors are not stored.
	Set(i uint64, e error)

	// Del removes the error stored at the given index.
	//
	// If no error exists at the index, this is a no-op. Note that deleting an error
	// does not "reclaim" its index or decrement the MaxId counter.
	//
	// Parameters:
	//   - i: The index of the error to remove.
	Del(i uint64)

	// Error aggregates all collected errors into a single error object.
	//
	// If the pool is empty, it returns nil.
	// If the pool contains exactly one error, that error is returned directly.
	// If multiple errors are present, they are combined using the main package's
	// hierarchical error structure (wrapped under liberr.UnknownError).
	//
	// Returns:
	//   - An aggregated error or nil.
	Error() error

	// Slice returns a snapshot of all errors currently in the pool.
	//
	// The errors are returned as a flat slice. Because the internal storage is a map,
	// the order of errors in the resulting slice is random and not guaranteed to
	// match the insertion order or index order.
	//
	// Returns:
	//   - A slice of errors, or nil if the pool is empty.
	Slice() []error

	// Len returns the current number of non-nil errors stored in the pool.
	//
	// This operation is highly efficient (O(1)) as it uses the underlying
	// atomic counter of the synchronized map.
	//
	// Returns:
	//   - The total count of errors.
	Len() uint64

	// MaxId returns the highest index ever assigned in this pool (via Add or Set).
	//
	// This provides a way to know the range of indices that have been used.
	// Note that this is a "high-water mark" and doesn't decrease if errors are deleted.
	//
	// Returns:
	//   - The maximum index value.
	MaxId() uint64

	// Last returns the error associated with the MaxId index.
	//
	// This is a convenience method for getting the "most recently" indexed error,
	// provided it hasn't been deleted.
	//
	// Returns:
	//   - The error at the highest index, or nil if not found.
	Last() error

	// Clear purges all errors from the pool and resets the MaxId high-water mark.
	//
	// Note: For performance reasons, the internal sequence counter used by Add()
	// is NOT reset, ensuring that if you continue using Add() after a Clear(),
	// new errors will have unique indices compared to the previous ones.
	Clear()
}

// New creates and initializes a new thread-safe error Pool.
// It is the standard way to instantiate a Pool implementation.
func New() Pool {
	return &mod{
		m: sync.RWMutex{},
		l: make([]error, 0, 10),
		s: new(atomic.Uint64),
	}
}
