/*
 * MIT License
 *
 * Copyright (c) 2026 Nicolas JUHEL
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Package errors implements an enterprise-grade error management framework for Go applications.
//
// Traditional Go error handling often lacks the context necessary for complex debugging,
// especially in distributed systems or multi-layered architectures. This package solves
// these challenges by providing a robust 'Error' interface that encapsulates numeric
// classification, automatic stack tracing, and hierarchical chaining of multiple errors.
//
// # Core Architecture: The Error Interface
//
// The central component is the Error interface, which extends the standard Go 'error'.
// Any error generated by this package carries:
//   - A CodeError: A uint16 numeric identifier (similar to HTTP status codes).
//   - A Message: A human-readable description, often localized or dynamically generated.
//   - A Stack Trace: The exact file, line, and function where the error originated.
//   - A Parent Chain: A list of other errors that caused this specific error.
//
// # Numeric Error Classification (CodeError)
//
// The CodeError type allows for machine-readable error handling. Instead of fragile
// string comparisons, developers can use numeric ranges.
//   - Range-Based Messages: You can register a message generator for a range of codes.
//     For example, codes 1000-1999 could be reserved for 'Database' errors.
//   - Collision Detection: The package provides tools to detect if two different
//     modules are trying to register overlapping error codes.
//
// # Hierarchical Error Chaining
//
// Unlike standard wrapping (fmt.Errorf("...: %w", err)), which creates a linear chain,
// this package supports a "one-to-many" hierarchy. One error can be caused by multiple
// underlying issues (e.g., a 'SystemFailure' caused by both 'NetworkTimeout' AND 'DiskFull').
// This hierarchy can be traversed using the Map() method or flattened using Slice() methods.
//
// # Automatic Stack Tracing
//
// Every time a new error is created (via New, Newf, or a CodeError constant), the
// package automatically captures the caller's stack frame.
//   - Intelligent Filtering: The trace system automatically strips out internal frames
//     from the 'runtime' package and the 'errors' package itself to keep logs clean.
//   - Vendor Sensitivity: It can detect if an error occurred within a 'vendor' directory
//     and adjust the path display accordingly.
//   - Custom Filters: You can customize how file paths are displayed using SetTracePathFilter.
//
// # Global Configuration: Error Modes
//
// The behavior of the Error() method is globally configurable via SetModeReturnError.
// This allows you to switch the output format for the entire application:
//   - ModeDefault: Standard message only.
//   - ModeReturnCode: Only the numeric code.
//   - ModeReturnCodeFull: Slice of all codes in the hierarchy.
//   - ModeReturnCodeError: "[Error #100] Message" (uses defaultPattern).
//   - ModeReturnCodeErrorFull: All codes and messages in hierarchy, newline-separated.
//   - ModeReturnCodeErrorTrace: "[Error #100] Message (file.go#42)" (uses defaultPatternTrace).
//   - ModeReturnCodeErrorTraceFull: Comprehensive output with codes, messages, and traces
//     for the entire parent chain, separated by newlines.
//   - ModeReturnStringError: Same as ModeDefault.
//   - ModeReturnStringErrorFull: All messages in hierarchy, newline-separated.
//
// This is extremely useful for switching between 'production' (minimal info) and
// 'development' (maximum debug info) environments without changing any business logic.
//
// # Customizing String Rendering (Patterns)
//
// You can globally customize the "glue" or formatting pattern used by the CodeError methods:
//   - SetDefaultPattern(pattern string): Changes the pattern for CodeError(). Default: "[Error #%d] %s"
//   - SetDefaultPatternTrace(pattern string): Changes the pattern for CodeErrorTrace(). Default: "[Error #%d] %s (%s)"
//
// These patterns are standard fmt-style strings.
//
// # Web Framework Integration (Gin)
//
// The package provides first-class support for the Gin Gonic framework via the ReturnGin interface.
//   - GinTonicAbort(ctx, httpCode): Immediately stops the request and returns a structured JSON.
//   - GinTonicErrorAbort(ctx, httpCode): Same as above, but also populates the ctx.Errors slice
//     with all errors in the hierarchy for logging middlewares.
//
// # Structured Returns
//
// The package defines a 'Return' interface to standardize how errors are serialized for APIs.
// The 'DefaultReturn' struct is a reference implementation that produces clean JSON:
//
//	{
//	  "code": "1001",
//	  "message": "database connection failed"
//	}
//
// # Detailed Usage & Factory Functions
//
// Beyond the basic CodeError.Error() method, several factory functions are available:
//   - New(code, msg, parents...): Basic constructor with stack trace capture.
//   - Newf(code, format, args...): Formatted message constructor.
//   - Make(err): Safely casts any standard error into the Error interface (adds no trace).
//   - IfError(code, msg, parents...): Only returns a new Error if at least one parent is not nil.
//   - AddOrNew(main, sub, parents...): Intelligent merging of multiple error sources.
//   - NewErrorRecovered(msg, recovered, parents...): Specifically designed for panic recovery,
//     capturing a deeper stack trace to find the root cause of the panic.
//
// # Navigation & Search
//
// Large error hierarchies can be interrogated using:
//   - HasCode(code): Recursive search for a specific code.
//   - HasError(err): Recursive search for an equivalent error.
//   - ContainsString(str): Recursive search for a substring in messages.
//   - Map(func): Manual traversal of the entire tree.
//
// # Quick Start Example
//
//	// 1. Define your codes
//	const (
//	    ErrInternal errors.CodeError = iota + 1000
//	    ErrDatabase
//	)
//
//	// 2. Register messages (usually in an init() function)
//	errors.RegisterIdFctMessage(ErrInternal, func(c errors.CodeError) string {
//	    switch c {
//	    case ErrInternal: return "internal system error"
//	    case ErrDatabase: return "database connection failed"
//	    default: return "unknown error"
//	    }
//	})
//
//	// 3. Use in your logic
//	func DoWork() error {
//	    if err := db.Connect(); err != nil {
//	        // Automatically captures stack trace and attaches 'err' as parent
//	        return ErrDatabase.Error(err)
//	    }
//	    return nil
//	}
//
// # Thread Safety Note
//
// While individual Error objects are safe for concurrent reading, they are not designed
// for concurrent modification. If you need to collect errors across multiple goroutines,
// use the 'pool' sub-package provided within this library.
package errors
