/*
 * MIT License
 *
 * Copyright (c) 2022 Nicolas JUHEL
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *
 */

package monitor

import (
	"encoding/json"
	"fmt"
	"strings"

	monsts "github.com/nabbar/golib/monitor/status"
	moninf "github.com/nabbar/golib/monitor/types"
	librun "github.com/nabbar/golib/runner"
)

const (
	// encTextSepStatus defines the separator between the status string and the detail sections in human-readable output.
	encTextSepStatus = ": "
	// encTextSepPart defines the main separator between data blocks (Name, Metrics, Message).
	encTextSepPart = " | "
	// encTextSepTime defines the internal separator for the metrics block (Latency / Uptime / Downtime).
	encTextSepTime = " / "
)

// Encode is an interface that defines the contract for converting a monitor's current state into various formats.
//
// Implementation Note:
// It is primarily used to generate human-readable strings or byte slices for logging, reporting,
// or API responses while ensuring consistency across formats.
type Encode interface {
	// String returns a formatted, human-readable string representation of the monitor's state.
	// Format: "<STATUS>: <Name> (<Info>) | <Latency> / <Uptime> / <Downtime> | <Message>"
	String() string

	// Bytes returns the byte slice representation of the string generated by String().
	Bytes() []byte
}

// encMod is a private concrete implementation of the Encode interface.
//
// Role:
// It acts as a Data Transfer Object (DTO) that captures a consistent snapshot of the monitor's
// state (status, metrics, metadata) for serialization purposes (JSON, Text).
type encMod struct {
	// Status represents the current health status (OK, Warn, KO).
	Status monsts.Status `json:"status"`

	// Name is the unique identifier of the monitored component.
	Name string `json:"name"`

	// Info contains additional metadata (version, etc.) about the monitor implementation.
	Info moninf.Info `json:"info"`

	// Latency is a human-readable string of the last check execution duration (e.g., "15ms").
	Latency string `json:"latency"`

	// LatencyInt is the last check execution duration in milliseconds.
	LatencyInt uint64 `json:"latency_ms"`

	// Uptime is a human-readable string of the total time spent in OK status (e.g., "2h 15m").
	Uptime string `json:"uptime"`

	// UpNum is the total uptime duration in seconds (Unix epoch style).
	UpNum uint64 `json:"uptime_epoc"`

	// Downtime is a human-readable string of the total time spent in non-OK statuses.
	Downtime string `json:"downtime"`

	// DownNum is the total downtime duration in seconds (Unix epoch style).
	DownNum uint64 `json:"downtime_epoc"`

	// Risetime is a human-readable string of the cumulative duration spent in "Rise" phase.
	Risetime string `json:"risetime"`

	// RiseNum is the total cumulative Rise duration in seconds.
	RiseNum uint64 `json:"risetime_epoc"`

	// Falltime is a human-readable string of the cumulative duration spent in "Fall" phase.
	Falltime string `json:"falltime"`

	// FallNum is the total cumulative Fall duration in seconds.
	FallNum uint64 `json:"falltime_epoc"`

	// Message contains the last error message captured, if any.
	Message string `json:"message"`
}

// Bytes returns the byte slice representation of the human-readable string.
func (e *encMod) Bytes() []byte {
	return []byte(e.String())
}

// String constructs and returns a human-readable representation of the snapshot.
// Sections are joined using standardized separators (encTextSepStatus, encTextSepPart).
func (e *encMod) String() string {
	return e.Status.String() + encTextSepStatus + e.stringPart()
}

// stringDuration is an internal helper that formats the metrics section (Latency, Uptime, Downtime).
func (e *encMod) stringDuration() string {
	part := append(make([]string, 0), e.Latency, e.Uptime, e.Downtime)
	return strings.Join(part, encTextSepTime)
}

// stringName is an internal helper that formats the identity section: "Name (Info)".
// If metadata is present, it is serialized via its own MarshalText implementation.
func (e *encMod) stringName() string {
	var inf string

	if e.Info != nil {
		i, _ := e.Info.MarshalText()
		inf = string(i)
	}

	if len(inf) > 0 {
		return fmt.Sprintf("%s (%s)", e.Name, inf)
	} else {
		return e.Name
	}
}

// stringPart aggregates identity, durations, and messages into the detail section of the string.
func (e *encMod) stringPart() string {
	item := make([]string, 0)
	item = append(item, e.stringName())
	item = append(item, e.stringDuration())

	if len(e.Message) > 0 {
		item = append(item, e.Message)
	}

	return strings.Join(item, encTextSepPart)
}

// getEncMod captures a consistent snapshot of the current monitor state and wraps it into an Encode object.
//
// Performance Detail:
// This method leverages the atomic-based 'l' metrics structure to ensure snapshot capture is non-blocking.
func (o *mon) getEncMod() Encode {
	defer func() {
		if r := recover(); r != nil {
			librun.RecoveryCaller("golib/monitor/encMod/getEncMod", r)
		}
	}()

	return &encMod{
		Status:     o.Status(),
		Name:       o.Name(),
		Info:       o.InfoGet(),
		Latency:    o.l.LatencyString(),
		LatencyInt: o.l.latencyMS(),
		Uptime:     o.l.upTimeString(),
		UpNum:      o.l.upTimeEpoc(),
		Downtime:   o.l.downTimeString(),
		DownNum:    o.l.downTimeEpoc(),
		Risetime:   o.l.riseTimeString(),
		RiseNum:    o.l.riseTimeEpoc(),
		Falltime:   o.l.fallTimeString(),
		FallNum:    o.l.fallTimeEpoc(),
		Message:    o.Message(),
	}
}

// MarshalText implements the encoding.TextMarshaler interface.
// This allows the monitor instance to be used directly by text-based encoders or logging frameworks.
func (o *mon) MarshalText() (text []byte, err error) {
	defer func() {
		if r := recover(); r != nil {
			librun.RecoveryCaller("golib/monitor/encMod/MarshalText", r)
		}
	}()

	return o.getEncMod().Bytes(), nil
}

// MarshalJSON implements the json.Marshaler interface.
// It generates a JSON byte slice representing the current snapshot of the monitor.
func (o *mon) MarshalJSON() (text []byte, err error) {
	return json.Marshal(o.getEncMod())
}
