/*
 * MIT License
 *
 * Copyright (c) 2022 Nicolas JUHEL
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *
 */

package info

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// Encode is an interface defining the contract for representing monitor information in a serializable format.
// It provides methods to generate both string and byte slice representations, typically used for logging,
// display, or as a component of larger status reports.
type Encode interface {
	// String returns a single-line, human-readable string representation of the component's identification data.
	// The standard format is: "ComponentName (key1: value1, key2: value2)".
	// If no metadata is present, it returns only the name.
	String() string

	// Bytes returns the byte slice representation of the string generated by String().
	// This is a convenience method for operations requiring a []byte instead of a string.
	Bytes() []byte
}

// encMod is a concrete implementation of the Encode interface, serving as a data transfer object (DTO)
// for the component's name and metadata. It is structured for easy serialization into JSON or text formats.
type encMod struct {
	// Name represents the resolved identifier of the component.
	Name string `json:"name"`
	// Data represents the collection of metadata associated with the component.
	Data map[string]interface{} `json:"data"`
}

// String constructs and returns the compact string representation of the metadata.
// It merges the component's name with its metadata string and ensures the result is cleaned
// of any multi-line characters (newlines, carriage returns).
func (e *encMod) String() string {
	if i := e.stringInfo(); len(i) > 0 {
		return e.stringClean(fmt.Sprintf("%s (%s)", e.Name, i))
	} else {
		return e.stringClean(e.Name)
	}
}

// Bytes returns the byte slice of the human-readable string representation.
func (e *encMod) Bytes() []byte {
	return []byte(e.String())
}

// stringInfo is an internal helper that serializes the metadata map into a comma-separated string.
// It iterates through the map and formats each entry as "key: value".
// The resulting string is trimmed of any trailing whitespace or commas.
func (e *encMod) stringInfo() string {
	var buf = bytes.NewBuffer(make([]byte, 0))
	for n, i := range e.Data {
		buf.WriteString(fmt.Sprintf("%s: %v,", n, i)) // nolint
	}
	return strings.Trim(strings.TrimSpace(buf.String()), ",")
}

// stringClean is an internal helper that sanitizes a string for single-line output.
// It replaces newline characters with spaces and removes carriage return characters entirely.
func (e *encMod) stringClean(str string) string {
	str = strings.Replace(str, "\n", " ", -1) // nolint
	str = strings.Replace(str, "\r", "", -1)  // nolint
	return str
}

// getEncodeModel is an internal method that captures a snapshot of the current 'inf' state
// and packages it into an object that implements the Encode interface.
func (o *inf) getEncodeModel() Encode {
	return &encMod{
		Name: o.Name(),
		Data: o.Data(),
	}
}

// MarshalText implements the encoding.TextMarshaler interface for the monitor info instance.
// This allows the instance to be used directly by text-based encoders, returning a cleaned,
// single-line human-readable string.
func (o *inf) MarshalText() (text []byte, err error) {
	return o.getEncodeModel().Bytes(), nil
}

// MarshalJSON implements the json.Marshaler interface for the monitor info instance.
// It leverages the encMod structure to provide a valid and structured JSON representation
// containing both the name and the metadata.
func (o *inf) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.getEncodeModel())
}
